# Site settings
site_name: AWS CDK Modules
site_url: https://collier-p-charlie.github.io/aws-cdk-modules/

# Repository settings
repo_name: collier-p-charlie/aws-cdk-modules
repo_url: https://github.com/collier-p-charlie/aws-cdk-modules/

# Theme settings
theme:
  name: material
  language: en
  font:
    text: montserrat
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - codehilite
  - toc:
      permalink: true

nav:
  - Home: index.md
